---
- name: deploy httpd server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: install nginx-light 
      apt:
        name: nginx-light
        state: latest

    - name: start & enabled nginx
      service:
        name: nginx
        state: started
        enabled: yes
